title = "Portio"
# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "en"

[languages.en.translations]
contact = "Hire Me Now"
see_details = "See Details"
sitemap = "Sitemap"
address = "Addresse"
phone = "Téléphone"
email = "Email"
opening_hours = "Working hours"
form_title = "Contact form"
form_button = "Send Message"
form_input_name = "Name"
form_input_email = "Email"
form_input_message = "Message"
form_input_agreement = "I agree that my submitted data is being collected and stored."

[extra]
logo = "images/logo.png"
google_analytics = "YOUR TOKEN FOR GOOGLE ANALYTICS"
formspree_url = "YOUR FORMSPREE URL"
copyright = "All right reserved copyright © Portio 2020"
display_cta = true


menus = [
  { name = "Home",    url = "#home" },
  { name = "About",   url = "#about" },
  { name = "Service", url = "#service" },
  { name = "Work",    url = "#portfolio" },
  { name = "Resume",  url = "#resume" },
  { name = "Blog",    url = "#blog" },
  { name = "Contact", url = "#contact" }
]

sitemaps = [
  { name = "About me", url = "#about" },
  { name = "Frequently Ask Question", url = "#" },
  { name = "Privacy & Policy", url = "#" },
  { name = "Latest Article", url = "#" }
]

socials = [
  { icon = "facebook-original", url = "https://www.facebook.com/" },
  { icon = "linkedin-original", url = "https://www.linkedin.com/" },
  { icon = "pinterest",         url = "https://www.pinterest.com" },
  { icon = "twitter-original",  url = "https://www.twitter.com" }
]

[extra.address]
phone = "+(448) 833 5272 332"
email = "hello@example.com"
address = "23 Khan Niketon, Grand Street, NYK."
opening_hours = "Open from 10am to 6pm (close at 5pm Sundays) "

# [extra.map]
# latitude = "14.022"
# longitude = "12.0665"

[extra.home]
enable = true
file = "static/data/home.toml"

[extra.about]
enable = true
file = "static/data/about.toml"

[extra.service]
enable = true
file = "static/data/service.toml"

[extra.portfolio]
enable = true
file = "static/data/portfolio.toml"

[extra.resume]
enable = true
file = "static/data/resume.toml"

[extra.skill]
enable = true
file = "static/data/skill.toml"

[extra.testimonial]
enable = true
file = "static/data/testimonial.toml"

[extra.blog]
enable = true
file = "static/data/blog.toml"