name = "portio-zola"
description = "It's a transcription of Portio-Hugo theme"
licence = "MIT"
homepage = "https://gitlab.com/quentin117/portio-zola.git"
min_version = "0.1.0"
demo = ""

[author]
name = "Quentin Rodriguez"
homepage = ""
repo = "https://gitlab.com/quentin117/portio-zola.git"

[original]
author = "Static Mania"
homepage = "https://staticmania.com/"
repo = "https://github.com/StaticMania/portio-hugo.git"
