name = "Portio-Zola"
description = "Portio-Zola is a minimal, well-formatted and extremely flexible theme"
licence = "MIT"
homepage = "https://github.com/quentin-rodriguez/portio-zola.git"
min_version = "0.20.0"
demo = "https://staticmania.com/"

[author]
name = "Quentin Rodriguez"
repo = "https://github.com/quentin-rodriguez/portio-zola.git"

[original]
author = "Static Mania"
repo = "https://github.com/StaticMania/portio-hugo.git"
